### ISSUE TITLE
Whenever Creating a user, i get an error

### ISSUE THREAD

**Issue by atreyaved** [Patitotective/Healeat#2]
Whenever i click , create user and fill in my detail and press "ok" , i get an error : 
Create window (<__main__.MainWindow object at 0x7f3845775a60>)
Traceback (most recent call last):
  File "/home/ved/Git-Repo/Healeat/Healeat/main.py", line 1259, in save_config
    self.prefs.write_prefs(f"users/{username}/sex", sex)
  File "/home/ved/.local/lib/python3.9/site-packages/PREFS/__init__.py", line 362, in write_prefs
    content = self.change_nested_dict_val(content, pref, value) # Calls method that change value of nested dictionaries.
  File "/home/ved/.local/lib/python3.9/site-packages/PREFS/__init__.py", line 390, in change_nested_dict_val
    scnDict = scnDict[i] # Set scnDict to scnDict key
KeyError: 'Ved'

**Comment by Patitotective** [comment]
If you keep getting the error, open the issue again.
